version: "3"
services:
  app-flask:
    container_name: flask-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    depends_on:
      - db-postgre
    volumes:
      - .:/app
    env_file:
      - .env
  db-postgre:
    container_name: postgre-db
    image: postgres:12
    ports:
      - "5454:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d

volumes:
  pgdata:
